
name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: linux-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.py

      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
          path: |
            artifacts/libwebroguelld.a
  
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    needs: [build-windows]
    steps:

    - uses: actions/download-artifact@v4
      with: 
        name: x86_64-unknown-linux-gnu
        path: x86_64-unknown-linux-gnu
      
    - name: make artifacts
      run: |
        mkdir artifacts
        cp artifacts_linux_x64_glibc/libwebroguelld.a artifacts/x86_64-unknown-linux-gnu

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*"
        name: Continuous build
        allowUpdates: true
        tag: latest_build
        commit: ${{ github.ref }}
        makeLatest: true
